[project]
name = "7-mcp-build-rich-context-ai-apps-with-anthropic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arxiv>=2.2.0",
    "mcp>=1.9.4",
]
